<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Giropay</name>
   <tag></tag>
   <elementGuidId>b88219bc-ea1d-47c0-91ba-57cf97eefd00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_GIROPAY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_GIROPAY']</value>
   </webElementProperties>
</WebElementEntity>
