<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iDEAL</name>
   <tag></tag>
   <elementGuidId>e86e836f-53df-4974-9c75-91fa4496b68b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_IDEAL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_IDEAL']</value>
   </webElementProperties>
</WebElementEntity>
