<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PayPal</name>
   <tag></tag>
   <elementGuidId>f1e0d1bd-4d1f-420d-bda0-8216da4591af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_PAYPAL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_PAYPAL']</value>
   </webElementProperties>
</WebElementEntity>
