<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SepaDD</name>
   <tag></tag>
   <elementGuidId>20cf7c02-8e03-4ac1-a7b6-870bf97bc662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_SEPA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'payment-method-options')]//input[@value='PG_SEPA']</value>
   </webElementProperties>
</WebElementEntity>
