<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Searchbox</name>
   <tag></tag>
   <elementGuidId>3f215d16-bbc1-411f-b636-ddaa9461b2e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@name='simpleSearch']//input[@id='q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@name='simpleSearch']//input[@id='q']</value>
   </webElementProperties>
</WebElementEntity>
