<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EUR001</name>
   <tag></tag>
   <elementGuidId>ae94d630-fe8b-453c-872e-f7edb91122de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='shipping-method-list']//input[@value='EUR001']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='shipping-method-list']//input[@value='EUR001']</value>
   </webElementProperties>
</WebElementEntity>
