<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bic</name>
   <tag></tag>
   <elementGuidId>82a257f9-4244-4f16-a2a8-d3ff68ba693d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='PaymentMethod_PG_GIROPAY']//input[contains(@name,'paymentGatewayBIC')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='PaymentMethod_PG_GIROPAY']//input[contains(@name,'paymentGatewayBIC')]</value>
   </webElementProperties>
</WebElementEntity>
