<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit</name>
   <tag></tag>
   <elementGuidId>31f424ba-3c0f-4eea-ac51-791643a9f3dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form//input[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form//input[@type='submit']</value>
   </webElementProperties>
</WebElementEntity>
