<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bic</name>
   <tag></tag>
   <elementGuidId>f20501e5-8c45-4ee4-bcae-c7f0e32b8f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='PaymentMethod_PG_EPS']//input[contains(@name,'paymentGatewayBIC')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='PaymentMethod_PG_EPS']//input[contains(@name,'paymentGatewayBIC')]</value>
   </webElementProperties>
</WebElementEntity>
