<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Switcher</name>
   <tag></tag>
   <elementGuidId>fe573c7a-d935-40e9-a6a2-dd9ddbf7f4ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='J_tip_qr']/a[@class='switch-tip-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='J_tip_qr']/a[@class='switch-tip-btn']</value>
   </webElementProperties>
</WebElementEntity>
